apps/admins/urls.py
from django.urls import path, include
from .views import (OaiRepoCreate,
    WebServiceCreate, deleterdr, get_oai,
    ScrapingCreate, list_admin,
    get_webservice, get_scraping,
    user_save, get_user,save_data_update_file,refreshWebService,deleteSource, 
    ApiReaderCreate, get_apireader, deleterdr, updaterdr
    
    )

app_name = 'admins' 

urlpatterns = [
    path('list_admin/', list_admin, name='list_admin'),
    path('user/', user_save, name='user_save'),
    path('uploadfile/',save_data_update_file,name="index" ),
    path('webservice/', WebServiceCreate, name='webservice'),
    path('scraping/', ScrapingCreate, name='scraping'),
    path('oai/', OaiRepoCreate, name='webservice'),
    path('get_webservice/', get_webservice, name='get_webservice'),
    path('get_oai/', get_oai, name='get_oai_repository'),
    path('get_scraping/', get_scraping, name='get_scraping'),
    path('get_user/', get_user, name='get_user'),
    path('refreshWebService/', refreshWebService, name="refreshWebService"),
    path('deleteSource/', deleteSource, name="deleteSource"),
    path('apireader/', ApiReaderCreate, name='apireader'),
    path('get_apireader/', get_apireader, name='get_apireader'),
    path('deleterdr/', deleterdr, name="deleterdr"),
     path('updaterdr/', updaterdr, name="updaterdr"),
     
]

apps/main/urls.py
from django.conf import settings
from django.views.generic import TemplateView
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *

app_name = 'main'

router = DefaultRouter()
router.register(r'category', TematicasViewSet, base_name="data")
router.register(r'statistics', StatisticsViewSet, base_name="data")

urlpatterns = [
   path('', indexView, name='home'),
   path('<categoria>', list_marine, name='marine'),
   path('category_fields/', category_fields, name='category-fields'),
   path('auth/login/', LoginAPI.as_view()),
   path('auth/', include('knox.urls')),
   path('oih/<str:categoria>', list_marine_OIH, name='OIH Metadata Expose'),
   path('oih/findid/<str:categoria>/<str:id_nombre>', findid, name='oih_find_id'),

   #path('<categoria>', Vessels_Info.as_view(), name='vessels-list'),   
   #url(r'^scraping/', webScraping.as_view(), name='scraping'),
   #url(r'^crawl/', views.crawl, name='crawl'),
]

urlpatterns += router.urls

# This is required for static files while in development mode. (DEBUG=TRUE)
# No, not relevant to scrapy or crawling :)
# if settings.DEBUG:
#     urlpatterns += static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.frontend.urls')),
    path('api/admins/',include('apps.admins.urls')),
    path('api/',include('apps.main.urls')),
    path('admin/', admin.site.urls), 
]

apps/main/views.py
from django.shortcuts import render,HttpResponse
from uuid import uuid4
from urllib.parse import urlparse
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator
from django.views.decorators.http import require_POST, require_http_methods
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from scrapyd_api import ScrapydAPI
from .models import People,Categoria,Institution,Document,Training,Laboratory, Platformgeo, Vessel
from .serializers import *
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.decorators import api_view, permission_classes
from rest_framework import generics
from rest_framework.decorators import api_view
from rest_framework import status, viewsets
from rest_framework.decorators import action
from django.views import View
from django_tables2 import RequestConfig
from django_tables2.views import SingleTableMixin
from .tables import PeopleTable, InstitutionTable,DocumentTable,TrainingTable, LaboratoryTable, PlatformgeoTable, VesselTable
from .filters import PeopleFilter, InstitutionFilter, DocumentFilter, TrainingFilter, LaboratoryFilter, PlatformgeoFilter, VesselFilter
from django.db.models import Q
import operator
from functools import reduce
from pprint import pprint
import json
from .helper import *
from knox.models import AuthToken
import hashlib
#from main.utils import URLUtil
#from main.models import ScrapyItem

# connect scrapyd service
scrapyd = ScrapydAPI('http://localhost:6800')

def encrypt_string(hash_string):
    sha_signature = hashlib.sha256(hash_string.encode()).hexdigest()
    return sha_signature


def indexView(request):
    template_name = "main/index.html"
    people = People.objects.all().count()
    institution = Institution.objects.all().count()
    document = Document.objects.all().count()
    training = Training.objects.all().count()
    laboratory = Laboratory.objects.all().count()
    platformgeo = Platformgeo.objects.all().count()
    vessel = Vessel.objects.all().count()
    context = {
        "people": people,
        "institution": institution,
        "document": document,
        "training": training,
        "laboratory": laboratory,
        "platformgeo": platformgeo,
        "vessel": vessel
    }
    return render(request, template_name,context)



def list_marine(request,categoria=None):
    context = {
        'table': None,
        'filter': None
    }
    table, f = None, None
    if categoria == "expert":
        queryset = People.objects.all()
        f = PeopleFilter(request.GET, queryset=queryset)
        table = PeopleTable(f.qs)
    elif categoria == "institution":
        queryset = Institution.objects.all()
        f = InstitutionFilter(request.GET, queryset=queryset)
        table = InstitutionTable(f.qs)
    elif categoria == "document":
        queryset = Document.objects.all()
        f = DocumentFilter(request.GET, queryset=queryset)
        table = DocumentTable(f.qs)
    elif categoria == "training":
        queryset = Training.objects.all()
        f = TrainingFilter(request.GET, queryset=queryset)
        table = TrainingTable(f.qs)
    elif categoria == "laboratory":
        queryset = Laboratory.objects.all()
        f = LaboratoryFilter(request.GET, queryset=queryset)
        table = LaboratoryTable(f.qs)
    elif categoria == "platformgeo":
        queryset = Platformgeo.objects.all()
        f = PlatformgeoFilter(request.GET, queryset=queryset)
        table = PlatformgeoTable(f.qs)
    elif categoria == "vessel":
        queryset = Vessel.objects.all()
        f = VesselFilter(request.GET, queryset=queryset)
        table = VesselTable(f.qs)
    if table:
        RequestConfig(request, paginate={'per_page': 10}).configure(table)
        context['table'] = table
    if f:
        context['filter'] = f
    return render(request, 'main/django_table.html', context)


@api_view(['GET'])
def list_marine_OIH(request,*args, **kwargs):
    base_url= "http://portete.invemar.org.co/chm/api/oih/"
    base_url2="http://portete.invemar.org.co/chm/api/oih/findid/"
    JsonResponse = {
    "@context": {
    "@vocab": "https://schema.org/"
    },
    "name": "Resource collection for https://CHM-LAC/",
    "@id": base_url + kwargs["categoria"]+'#'+encrypt_string(kwargs["categoria"]),
    "@type":[
            "ItemList",
        ],
    "author": {
        "@id": encrypt_string("Instituto de Investigaciones Marinas y Costeras INVEMAR"),
        "@type": "Organization",
        "name": "Instituto de Investigaciones Marinas y Costeras INVEMAR",
        "sameAs": [
            "https://oceanexpert.org/institution/6795"
        ]
    },
    "itemListOrder": "https://schema.org/ItemListUnordered",
    "numberOfItems": 0,
    "itemListElement": []    
    }

    if kwargs["categoria"] == "documents":


        documents = Document.objects.all().values()
        JsonResponse["@type"].append("CreativeWork")
        
        for doc in documents:
            print(doc["shared"])
            if doc["json_ld"] is not None and len(doc["json_ld"])>=1 :
                if doc["shared"] is not False:
                    JsonResponse["numberOfItems"] += 1 
                    JsonResponse["itemListElement"].append(json.loads(doc["json_ld"]))
            else:
                if doc["shared"] is not False:
                    JsonResponse["numberOfItems"] += 1 
                    JsonResponse["itemListElement"].append({
                        "@type": "ListItem",
                        "position": JsonResponse["numberOfItems"],
                        "item":
                            {
                                "@id": base_url2 + kwargs["categoria"]+'/'+encrypt_string(doc["id_nombre"]),
                                "@context": {
                                    "@vocab": "https://schema.org/"
                                },
                                "@type": "CreativeWork",
                                "name": doc["nombre"],
                                "description": doc["resumen"],
                                "url": doc["url"],
                                "thumbnailUrl": doc["imagen"]
                            }
                        })  
    elif kwargs["categoria"] == "institution":
        queryset = Institution.objects.all().values()
        JsonResponse["@type"].append("Organization")
        for inst in queryset:
            JsonResponse["numberOfItems"] += 1 
            JsonResponse["itemListElement"].append({
                "@type": "ListItem",
                "position": JsonResponse["numberOfItems"],
                "item":
                    {
                        "@id": base_url2 + kwargs["categoria"]+'/'+encrypt_string(inst["id_nombre"]),
                        "@context": {
                            "@vocab": "https://schema.org/"
                        },
                        "@type": "Organization",
                        "name": inst["nombre"],
                        "url": inst["url"],
                        "address": {
                            "@type": "PostalAddress",
                            "addressLocality": inst["pais"],
                            # "postalCode": "F-75002",
                            "streetAddress": inst["direccion"]
                        },
                        # "datePublished": inst["date_published"],
                        # "dateModified": inst["date_modified"],
                        # "image": inst["imagen"],
                        "thumbnailUrl": inst["imagen"]
                    }
                })
    elif kwargs["categoria"] == "expert":
        queryset = People.objects.all().values()
        JsonResponse["@type"].append("Person")
        for pep in queryset:
            JsonResponse["numberOfItems"] += 1 
            JsonResponse["itemListElement"].append({
                "@type": "ListItem",
                "position": JsonResponse["numberOfItems"],
                "item":
                    {
                        "@id": base_url2 + kwargs["categoria"]+'/'+encrypt_string(pep["id_nombre"]),
                        "@context": {
                            "@vocab": "https://schema.org/"
                        },
                        "@type": "Person",
                        "name": pep["nombre"],
                        "url": pep["url"],
                        "jobTitle": pep["ocupacion"],
                        "affiliation":pep["institucion"],
                        "nationality": [
                            {
                            "@type": "Country",
                            "name": pep["pais"]
                            },
                        ],
                        "knowsAbout":pep["aptitudes"],
                        "thumbnailUrl": pep["imagen"]
                        
                    }
                })
    elif kwargs["categoria"] == "training":
        queryset = Training.objects.all().values()
        JsonResponse["@type"].append("LearningResource")
        JsonResponse["@type"].append("CreativeWork")
        for inst in queryset:
            JsonResponse["numberOfItems"] += 1 
            JsonResponse["itemListElement"].append({
                "@type": "ListItem",
                "position": JsonResponse["numberOfItems"],
                "item":
                    {
                        "@id": base_url2 + kwargs["categoria"]+'/'+encrypt_string(inst["id_nombre"]),
                        "@context": {
                            "@vocab": "https://schema.org/"
                        },
                        "@type": "Course",
                        "name": inst["nombre"],
                        "email": inst["email"],

apps/main/templates/main/base.1.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CHM/TMT</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'main/index/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/index/css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'main/index/css/styles.css' %}" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="{% static 'main/index/css/2-col-portfolio.css' %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">CHM/TMT</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Page Content -->
    {% block content%} {% endblock %}
     <!-- <div class="container"  >
          <div class="container-inside" >
              
          </div>   
      </div>-->
   
   
    <!-- /.container -->

   
    <!-- Footer -->
    <footer class="bg-dark tmfoot">
        <div class="container">
          <p class="m-0 text-center text-white">Copyright &copy; CHM/TMT 2019</pS>
        </div>
        <!-- /.container -->
    </footer>
   
    

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'main/index/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'main/index/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </body>

</html>

apps/main/templates/main/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'main/index/css/bootstrap1.min.css' %}" />
    <link rel="stylesheet" href="{% static 'main/index/css/bootstrap-select.min.css' %}" />
    <link rel="stylesheet" href="{% static 'main/index/css/animate.min.css' %}" />
    <link rel="stylesheet" href="{% static 'main/index/css/styles.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Font-awesome -->
    <link rel="stylesheet" href="{% static 'main/index/css/font-awesome.min.css' %}" />

    <title>CHM LAC</title>
  </head>
  <body>
    <main>
        <header class="h fixed-top">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
              <div class="container">
                <button
                  class="navbar-toggler"
                  type="button"
                  data-toggle="collapse"
                  data-target="#navbarTogglerDemo03"
                  aria-controls="navbarTogglerDemo03"
                  aria-expanded="false"
                  aria-label="Toggle navigation"
                >
                  <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="{% url 'main:home' %}">
                  <img class="logo-web" src="{% static 'main/index/images/logo-web.svg' %}" alt="OceanFinder"
                /></a>
    
                <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                  <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'main:home' %}"
                        >Home <span class="sr-only">(current)</span></a
                      >
                    </li>
                    <!-- <li class="nav-item"><a class="nav-link" href="#">Link</a></li> -->
                    <li class="nav-item"><a class="nav-link" href="{% url 'admins:index'  %}">Upload File</a></li>
                  </ul>
                  <a
                    class="btn btn-link"
                    data-toggle="tooltip"
                    data-placement="bottom"
                    title="Español"
                  >
                  <img src="{% static 'main/index/images/es.svg' %}" alt="" style="width: 20px;" />
                  </a>
                  <a
                    class="btn btn-link disabled"
                    data-toggle="tooltip"
                    data-placement="bottom"
                    title="English"
                  >
                  <img src="{% static 'main/index/images/us.svg' %}" alt="" style="width: 20px;" />
                  </a>
                </div>
              </div>
            </nav>
          </header>
      {% block content %} {% endblock%}
    </main>

    <footer>
      <div class="container">
        <div class="row align-items-center">
          <div class="col">©2019, CHM LAC. All rights reserved.</div>
        </div>
      </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
      integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'main/index/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'main/index/js/bootstrap-select.min.js' %}"></script>
    
  </body>
</html>

apps/main/templates/main/django_table.html
{% extends "main/base.html" %}
{% load querystring from django_tables2 %}
{% load render_table from django_tables2 %}
{% load widget_tweaks %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />


{% block content %}

<section class="banner-search">
        <div class="container">
          <div class="row align-items-center pb-2">
            <!--Busqueda para mobiles-->
            <div class="col-md-6 d-sm-none">
              <form>
                <div class="form-row">
                  <div class="col">
                    <div class="form-group">
                      <input
                        type="text"
                        class="form-control"
                        placeholder="Search"
                      />
                    </div>
                  </div>
                  <div class="col-sm-4">
                    <div class="form-group">
                      <select class="selectpicker form-control">
                        <option>Experts</option>
                        <option>Documents</option>
                        <option>Training</option>
                        <option>Laboratories</option>
                        <option>Institutions</option>
                        <option>Geographic platforms</option>
                        <option>Vassels</option>
                      </select>
                    </div>
                  </div>
                  <div class="col-sm-3">
                    <button type="submit" class="btn btn-primary">
                      Search
                    </button>
                  </div>
                </div>
              </form>
            </div>
            <!--Fin de busqueda para mobiles-->

            <!--Busqueda para web-->
            <!-- <div class="col-md-6 d-none d-sm-block">
              <form method="get">
                <div class="input-wi">
                  <div class="input-group mb-3">                 
                  {% render_field filter.form.nombre class="form-control" placeholder="Search name" %}
                  <i class="fa fa-search" aria-hidden="true"></i>
                  <div class="input-group-append">                    
                    <button type="submit" class="btn btn-primary">
                            <span class="glyphicon glyphicon-search"></span> Search
                    </button>
                  </div>
                </div>
                </div>
              </form>
            </div> -->
            <!--Fin de busqueda para web-->
          </div>
        </div>
        <div class="container d-none d-sm-block">
          
          <ul class="nav nav-tabs">
            <li class="nav-item">
              <a class="nav-link {% if request.path|slice:":18" == '/chm/marine/expert' %}active{% endif %} " href="{% url 'main:marine' 'expert' %}">Experts</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.path|slice:":20" == '/chm/marine/document' %}active{% endif %}" href="{% url 'main:marine' 'document' %}">Documents</a></li>
            <li class="nav-item"><a class="nav-link {% if request.path|slice:":20" == '/chm/marine/training' %}active{% endif %}" href="{% url 'main:marine' 'training' %}">Training</a></li>
            <li class="nav-item">
              <a class="nav-link {% if request.path|slice:":22" == '/chm/marine/laboratory' %}active{% endif %}" href="{% url 'main:marine' 'laboratory' %}">Laboratories</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path|slice:":23" == '/chm/marine/institution' %}active{% endif %}" href="{% url 'main:marine' 'institution' %}">Institutions</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path|slice:":23" == '/chm/marine/platformgeo' %}active{% endif %}" href="{% url 'main:marine' 'platformgeo' %}">Geospatial information</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path|slice:":23" == '/chm/marine/vessel' %}active{% endif %}" href="{% url 'main:marine' 'vessel' %}">Vessel information</a>
            </li>
          </ul>
        </div>
      </section>

      <section class="resultados">
        <div class="container">
          <!-- <div class="">
            <div class="row align-items-center pb-2">
              <div class="col-md-6 d-none d-sm-block">
                <form method="get">
                  <div class="input-wi">
                    <div class="input-group mb-3">                 
                    {% render_field filter.form.nombre class="form-control" placeholder="Search name" %}
                    <i class="fa fa-search" aria-hidden="true"></i>
                    <div class="input-group-append">                    
                      <button type="submit" class="btn btn-primary">
                              <span class="glyphicon glyphicon-search"></span> Search
                      </button>
                    </div>
                  </div>
                  </div>
                </form>
              </div>
            </div>
          </div>  -->
          <div class="row">
            <div class="col-md-12">
              <!--<button type="button" class="btn btn-primary float-right">
                Filter <i class="icon-plus"></i>
              </button>
              <h4>Experts</h4>
              <p class="lean">
                Showing results <b>21-30</b> of <b>171</b> for <i>Beatri</i>
              </p>

              <hr />-->
            
            <form method="get">
              <div style="margin-bottom: 20px;">
                <h5>Filters</h5>
                <div class="form-row">
                  <!--<div class="col-sm-2">
                    <div class="form-group">
                      <select class="selectpicker form-control">
                        <option>Name contains</option>
                        <option>Activites include</option>
                        <option>Country is</option>
                        <option>Department contains</option>
                        <option>Institution name contains</option>
                        <option>Job type is</option>
                      </select>
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-group">
                      <input
                        type="text"
                        class="form-control"
                        placeholder="Search"
                      />
                    </div>
                  </div>

                  <div class="col-sm-3">
                    <button type="submit" class="btn btn-primary">
                      Filter <i class="icon-plus"></i>
                    </button>
                  </div>-->
                  <!-- <div class="col-md-6 d-none d-sm-block">
                    <form method="get">
                      <div class="input-wi">
                        <div class="input-group mb-3">                 
                        {% render_field filter.form.nombre class="form-control" placeholder="Search name" %}
                        <i class="fa fa-search" aria-hidden="true"></i>
                        <div class="input-group-append">                    
                          <button type="submit" class="btn btn-primary">
                                  <span class="glyphicon glyphicon-search"></span> Search
                          </button>
                        </div>
                      </div>
                      </div>
                    </form>
                  </div>                    -->
                </div>
                <div class="form-row">
                  {% if filter.form.nombre %}
                    <div class="form-group col-sm-4 col-md-3">
                      {{ filter.form.nombre.label_tag }}
                      {% render_field filter.form.nombre class="form-control" placeholder="Search name" %}
                    </div>
                    
                  {%  endif %}
                  {% if filter.form.ocupacion %}
                    <div class="form-group col-sm-4 col-md-3">
                            {{ filter.form.ocupacion.label_tag }}
                            {% render_field filter.form.ocupacion class="form-control" placeholder="Search occupation" %}
                    </div>
                    <div class="form-group col-sm-4 col-md-3">
                            {{ filter.form.institucion.label_tag }}
                            {% render_field filter.form.institucion class="form-control" placeholder="Search institution" %}
                    </div>
                  {% endif %} 

                  
                </div>
                
                <button type="submit" class="btn btn-primary">
                      <span class="glyphicon glyphicon-search"></span> Search
                </button>
                
              </div>
            
            
            </form>
        </div>
    </div>
          {% if filter %}
              {% render_table table %}
          {% endif %}
        

        <!--<nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
            <li class="page-item active">
              <a class="page-link" href="#">1</a>
            </li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
          </ul>
        </nav>-->
      </section>
    </div>

<!--ANTIGUO -->





    
    
{% endblock %}